### ISSUE TITLE
SOVERSION should be set manually

### ISSUE THREAD

**Issue by dawidd6** [paolostivanin/libcotp#18]
Hello, i think that SOVERSION in CMakeLists.txt should be set manually as a standalone number and bumped when ABI changes, because now after transition from 1.0.14 to 1.1.0 SOVERSION stays the same, which is wrong because of these ABI changes.

https://github.com/paolostivanin/libcotp/blob/d3d1ebe3d255fefd6629bd58086d8435fdf14b78/CMakeLists.txt#L35

or maybe change BUILD_MAJOR to BUILD_MINOR?

**Comment by paolostivanin** [comment]
Hi,
Thanks for reporting this. You are absolutely right, I'm gonna fix it later today! :grinning:
