### ISSUE TITLE
investigate potential regression in 1.2.0

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/libcotp#23]
https://github.com/paolostivanin/libcotp/pull/22#issuecomment-414078211

**Comment by paolostivanin** [comment]
@magiruuvelvet please let's continue the discussion here, thx :)

**Comment by magiruuvelvet** [comment]
`DIGITS_POWER[digits_length]`

There is an array out of bound when the digit size is greater than 8. I just increased the array with more values.

**Comment by paolostivanin** [comment]
Yep, you're right! I was able to reproduce the issue with >= 15 digits. Increasing the array size is not enough though, there are some other fixes needed :)

**Comment by paolostivanin** [comment]
Support tokens with long digits (> 10) would require a bigger refactoring. 
I looked online and no one is using more than 8 digits, so for the time being the max supported digits will be 10
