### ISSUE TITLE
Exception running...

### ISSUE THREAD

**Issue by GuoxinL** [paolostivanin/libcotp#26]
```
#include <stdio.h>
#include <cotp.h>
#include <time.h>
int main() {

    const char *base32_encoded_secret = "1234567890";
    int digits = 5;
    int period = 20;
    int algo = SHA1;
    cotp_error_t *err = NULL;
    char *fds = "1234";
    printf("%s", fds);
//    char *totp = get_steam_totp(base32_encoded_secret, 3, err);
    char *totp = get_hotp(base32_encoded_secret, digits, period, SHA512, err);
    printf("%s", totp);

}
```
![image](https://user-images.githubusercontent.com/19989609/63328031-f6b7de80-c361-11e9-862d-d22fe097762d.png)
Is there anything wrong with the parameters I filled in？

**Comment by paolostivanin** [comment]
Hello,
the function definition for `get_hotp` is
```
char *
get_hotp(const char *secret, long timestamp, int digits, int algo, cotp_error_t *err_code)
```

maybe you confused it with `get_totp`:
```
char *
get_totp(const char *secret, int digits, int period, int algo, cotp_error_t *err_code)
```

**Comment by GuoxinL** [comment]
Here's what I want to achieve ”Time-based One-time Password“,Is it correct to use the following method
`char *
get_totp(const char *secret, int digits, int period, int algo, cotp_error_t *err_code)`

**Comment by paolostivanin** [comment]
yep, that's the one :+1:

**Comment by GuoxinL** [comment]
![image](https://user-images.githubusercontent.com/19989609/63329746-1ac8ef00-c365-11e9-98db-43001ba84f1e.png)
Thank you very much for your patient answer，Run~
