### ISSUE TITLE
No package 'baseencode' found

### ISSUE THREAD

**Issue by Josh68** [paolostivanin/libcotp#30]
Hello. I'm getting the error `No package 'baseencode' found` trying to update libcotp/otpclient. I can install [libbaseencode](https://github.com/paolostivanin/libbaseencode) manually, but not this package afterward, either manually or through a package manager.

Thanks

**Comment by paolostivanin** [comment]
very weird, because it's working fine on all systems here (archlinux, opensuse, ubuntu, debian). What are you doing exactly?

See here for hints: https://github.com/paolostivanin/OTPClient/blob/master/.ci/install_deps.sh

**Comment by Josh68** [comment]
I just ran a large update after being away from Manjaro for a while, and this issue mysteriously resolved itself. So closing. Thanks.
