### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [paolostivanin/libcotp#32]
As per title: `cotp.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to broken .pc files on NixOS in particular.

Identical to https://github.com/paolostivanin/libbaseencode/issues/25. See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by paolostivanin** [comment]
Thanks for having found and reported this bug, I'm on it :)

**Comment by alexshpilkin** [comment]
@paolostivanin Could you port the change from https://github.com/paolostivanin/libbaseencode/commit/3f37e655b7c5a522a5e386cdea50cc19e629ed1a here as well?

**Comment by paolostivanin** [comment]
it's already present in v1.2.6
