### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by harshraj21** [paolostivanin/libcotp#43]
`CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  CMakeLists.txt:8 (find_package)`

Any idea why this error and how to fix this?

**Comment by paolostivanin** [comment]
Hello,
you are missing `pkg-config` . You can install it with:
* `sudo apt install pkg-config`
* `sudo zypper in pkgconf-pkg-config`
* `sudo pacman -S pkgconf`

**Comment by harshraj21** [comment]
i am still getting dependency error while building on ubuntu 20 (Focal), The package being installed is older version than required, can you upload an already built library for this, will it be possible for you?

**Comment by paolostivanin** [comment]
Hello,
I have a PPA for all Ubuntu LTS: https://launchpad.net/~polslinux/+archive/ubuntu/otpclient

**Comment by harshraj21** [comment]
Thanks <3
