### ISSUE TITLE
base32_encode returns an error when the leading byte is 0

### ISSUE THREAD

**Issue by TetraK1** [paolostivanin/libcotp#54]
base32_encode passes the byte array to check_input, which returns an error if the first byte is 0.

This fails when it shouldn't i.e. 0 is a valid secret.
```
uint8_t secret_bytes[] = {0, 0, 0, 0};
cotp_error_t err_code;
base32_encode(secret_bytes, 4, &err_code);
// err_code = EMPTY_STRING
```

**Comment by paolostivanin** [comment]
You're right, thanks for reporting this! I'll fix it in the next days

**Comment by paolostivanin** [comment]
fixed with https://github.com/paolostivanin/libcotp/commit/00c55ccb37a424511d568b85ebb7577ef9a20103
