### ISSUE TITLE
openssl 1.1 support

### ISSUE THREAD

**Issue by calvin2021y** [paolostivanin/libcotp#62]
can not build with openssl 1.1.1w

**Comment by paolostivanin** [comment]
it requires 3.0 (https://github.com/paolostivanin/libcotp/blob/60461cd28c297eed476ff93d9b1123c3855c7053/CMakeLists.txt#L26C18-L26C34)

openSSL 3.0 is available basically on every distro, so this older openSSL version won't be supported.
