### ISSUE TITLE
Error during compilation!

### ISSUE THREAD

**Issue by chen-tk** [paolostivanin/libcotp#64]
When I am using libgcrypto to compiling (with cmake command "cmake . -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=$PWD/built -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DGCRYPT_LIBRARIES=build/lib -DGCRYPT_INCLUDE_DIR=build/include") , gcc throwed an error: 

D:\Desktop\libcotp\src\whmac.h:27:1: error: unknown type name 'ssize_t'
   27 | ssize_t         whmac_finalize   (whmac_handle_t *hd,
      | ^
D:\Desktop\libcotp\src\otp.c:239:12: warning: 'strdup' is deprecated: The POSIX name for this item is deprecated.
      Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
  239 |     return strdup (code);
      |            ^
E:\Windows Kits\10\Include\10.0.22621.0\ucrt\string.h:531:20: note: 'strdup' has been explicitly marked deprecated here
  531 |     _Check_return_ _CRT_NONSTDC_DEPRECATE(_strdup)
      |                    ^
E:\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt.h:428:50: note: expanded from macro '_CRT_NONSTDC_DEPRECATE'
  428 |         #define _CRT_NONSTDC_DEPRECATE(_NewName) _CRT_DEPRECATE_TEXT(             \
      |                                                  ^
E:\Microsoft Visual Studio\Community\VC\Tools\MSVC\14.39.33519\include\vcruntime.h:345:47: note: expanded from macro
      '_CRT_DEPRECATE_TEXT'
  345 | #define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
      |                                               ^
D:\Desktop\libcotp\src\otp.c:302:5: error: use of undeclared identifier 'ssize_t'; did you mean 'sizeof'?
  302 |     ssize_t flen = whmac_finalize (hd, hmac, dlen);
      |     ^~~~~~~
      |     sizeof
D:\Desktop\libcotp\src\otp.c:302:13: error: use of undeclared identifier 'flen'; did you mean 'dlen'?
  302 |     ssize_t flen = whmac_finalize (hd, hmac, dlen);
      |             ^~~~
      |             dlen
D:\Desktop\libcotp\src\otp.c:294:12: note: 'dlen' declared here
  294 |     size_t dlen = whmac_getlen (hd);
      |            ^
D:\Desktop\libcotp\src\otp.c:303:9: error: use of undeclared identifier 'flen'; did you mean 'dlen'?
  303 |     if (flen < 0) {
      |         ^~~~
      |         dlen
D:\Desktop\libcotp\src\otp.c:294:12: note: 'dlen' declared here
  294 |     size_t dlen = whmac_getlen (hd);
      |            ^
1 warning and 4 errors generated.

**PS: I am Chinese, so my English is not very well. Don't care please : )**

**Comment by chen-tk** [comment]
Emmm... I seem to have succeeded. But there are many warnings when I was compiling the static library.

**Comment by paolostivanin** [comment]
sorry, but non-linux environment are not supported!

**Comment by chen-tk** [comment]
But I compiled it successfully(on windows) by mingw, clang and msvc. and here was no error when I used mingw(maybe it was because I replaced size_t with long long?)
