### ISSUE TITLE
compute_hmac assumes little-endian

### ISSUE THREAD

**Issue by pem** [paolostivanin/libcotp#67]
The function compute_hmac reverses the bytes in "C" on the assumption that it's little endian.
This doesn't work on big endian architectures, like sparc (Solaris), PowerPC (AIX and Linuxes on PPC), and ARM. (The latter two can be either little or big endian.

**Comment by paolostivanin** [comment]
hello,
yes, you're right, it assumes the CPU is LE.
I never had anyone interested in BE, so I never implemented it.

Looks like I know what to do for the next release :)

**Comment by paolostivanin** [comment]
@pem would you be able to test the fix on a big endian machine? It would be fantastic if you could install criterion and run all the tests

**Comment by paolostivanin** [comment]
I was able to test it on a s390x machine, works fine!
